spring:
  application:
    name: internship-backend
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    # password: ${DB_PASSWORD:password}
    # url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:internship}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:intership}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

mailjet:
  key: ${MAILJET_API_KEY:}
  secret: ${MAILJET_API_SECRET:}